---
- hosts: LinuxCentos:LinuxUbuntu:LinuxFreeBSD
  tasks:
  - name: create directory with parent directories
    file:
     path: /root/.ssh/
     state: directory
    when: (ansible_facts['system'] == "Linux")

# Synchronization using rsync protocol on delegate host (pull)
  - synchronize:
    mode: pull
    src: rsync://192.168.10.1/root/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
   when: (ansible_facts['system'] == "Linux")

#Set Time Zone
  - name: Ajustando o timezone do sistema
    timezone: name=America/Sao_Paulo
    when: (ansible_facts['system'] == "Linux")

#SELINUX
  - name: Desabilitando o SeLinux
    selinux: state=disabled
    when: (ansible_facts['system'] == "Linux" and ansible_facts['selinux_python_present'] == "Linux")

  - name: Add packages on FreeBSD
    pkgng:
      name: rsync,bash,most,bash-completion,vnstat,htop,wget,curl
    when: (ansible_facts['system'] == "FreeBSD")
